/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pe.farmaciasperuanas.posunificado.mybatis;

import mifarma.common.FarmaVariables;
import org.apache.ibatis.session.SqlSessionFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.math.BigDecimal;
import java.util.HashMap;
import java.util.Map;
import java.util.Optional;

public class App {

    private static final Logger log = LoggerFactory.getLogger(App.class);

    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());

        FarmaVariables.vCodGrupoCia = "001";
        FarmaVariables.vCodCia = "001";

        FarmaVariables.vIPBD = "127.0.0.1";
        FarmaVariables.vUsuarioBD = "";
        FarmaVariables.vClaveBD = "";
        FarmaVariables.vSID = "XE";

        double tc = getTipoCambio("30/03/2022", "V");
        log.info("T.C.: {}",tc);
    }

    /**
     * Obtiene tipos de cambio
     * @author ERIOS
     * @since 18.11.2013
     */
    public static double getTipoCambio(String pFecha, String pTipo) {
        BigDecimal vTipoCambio = null;

        Map<String, Object> mapParametros = new HashMap<>();
        mapParametros.put("cCodGrupoCia_in", FarmaVariables.vCodGrupoCia);
        mapParametros.put("cCodCia_in", FarmaVariables.vCodCia);
        mapParametros.put("cFecCambio_in", pFecha);
        mapParametros.put("cTipo", pTipo);

        SqlSessionFactory sqlSessionFactory = MyBatisUtil.getSqlSessionFactory();

        try (var sqlSession = sqlSessionFactory.openSession()) { //.1
            MapperRecaudacion mapper = sqlSession.getMapper(MapperRecaudacion.class);
            mapper.getTipoCambio3(mapParametros);
            vTipoCambio = (BigDecimal)mapParametros.get("nValorTipoCambio");
        } catch (Exception e) {
            log.error("", e);
        }

        //return vTipocambio?:0.0
        //return vTipoCambio == null?0.0:vTipoCambio.doubleValue();
        return Optional.ofNullable(vTipoCambio)
                .map(BigDecimal::doubleValue)
                .orElse(0.0); //.3
    }
}
